package domain.ui.webstudio.pages.mainpages;

import com.microsoft.playwright.Page;
import configuration.core.ui.WebElement;
import domain.ui.webstudio.components.common.TabSwitcherComponent;
import domain.ui.webstudio.components.repositorytabcomponents.CompareGitRevisionsDialogComponent;
import domain.ui.webstudio.components.repositorytabcomponents.SyncUpdatesDialogComponent;
import domain.ui.webstudio.components.common.ConfigureCommitInfoComponent;
import domain.ui.webstudio.components.projectdetail.ProjectFilesTabComponent;
import domain.ui.webstudio.components.projectdetail.ProjectHeaderActionsComponent;
import domain.ui.webstudio.components.projectdetail.ProjectHistoryTabComponent;
import domain.ui.webstudio.components.projectdetail.ProjectOverviewTabComponent;
import domain.ui.webstudio.components.repositorytabcomponents.CopyProjectDialogComponent;
import domain.ui.webstudio.components.repositorytabcomponents.ExportProjectModalComponent;
import domain.ui.webstudio.pages.BasePage;
import helpers.utils.WaitUtil;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import lombok.Getter;

import java.util.List;

// React project-detail view (/projects/<id>) introduced in build 032c60a664ce: Overview / Files /
// History / Branches / Publish tabs. Reached from the projects list via RepositoryPage.openProjectDetail.
public class ProjectDetailPage extends BasePage {

    private static final Logger LOGGER = LogManager.getLogger(ProjectDetailPage.class);

    // Header buttons render with the screen, so a short probe decides bar-vs-overflow.
    private static final int HEADER_ACTION_PROBE_MS = DEFAULT_TIMEOUT_MS / 5;
    // The detail screen can settle after the first tab click, so a switch may need repeating.
    private static final int TAB_SWITCH_ATTEMPTS = 3;
    private static final int COMPARE_WINDOW_WIDTH = 1280;
    private static final int COMPARE_WINDOW_HEIGHT = 800;

    // Top navigation (shared React shell)
    @Getter
    private TabSwitcherComponent tabSwitcherComponent;
    // Tabs
    private WebElement overviewTab;
    private WebElement filesTab;
    private WebElement historyTab;
    // Scoped sub-components of the detail view
    private ProjectHeaderActionsComponent headerActions;
    private ProjectOverviewTabComponent overview;
    private ProjectFilesTabComponent files;
    private ProjectHistoryTabComponent history;
    // Open Revision dialog (antd portal)
    private WebElement openRevisionSelect;
    private WebElement openRevisionOption;
    private WebElement openRevisionSubmit;
    private List<WebElement> openRevisionOptions;
    private ExportProjectModalComponent exportProjectModalComponent;
    private WebElement mergeTargetBranchSelect;
    private List<WebElement> mergeBranchOptions;
    private CopyProjectDialogComponent copyProjectDialogComponent;
    private ConfigureCommitInfoComponent configureCommitInfoComponent;
    private WebElement configureCommitInfoShade;
    private SyncUpdatesDialogComponent syncUpdatesDialogComponent;
    private WebElement detailRoot;

    public ProjectDetailPage() {
        super();
        initializeComponents();
    }

    private void initializeComponents() {
        tabSwitcherComponent = createScopedComponent(TabSwitcherComponent.class, "xpath=//ul[@role='menu' and contains(@class,'ant-menu-horizontal')]", "tabSwitcherComponent");
        overviewTab = new WebElement(page, "xpath=//div[@data-node-key='overview']", "overviewTab");
        filesTab = new WebElement(page, "xpath=//div[@data-node-key='files']", "filesTab");
        historyTab = new WebElement(page, "xpath=//div[@data-node-key='history']", "historyTab");
        headerActions = new ProjectHeaderActionsComponent(page);
        overview = new ProjectOverviewTabComponent(page);
        files = new ProjectFilesTabComponent(page);
        history = new ProjectHistoryTabComponent(page);
        openRevisionSelect = new WebElement(page, "[data-testid=open-revision-select]", "openRevisionSelect");
        openRevisionOption = new WebElement(page, "xpath=//div[contains(@class,'ant-select-item-option')][@title='%s']", "openRevisionOption");
        openRevisionSubmit = new WebElement(page, "[data-testid=open-revision-submit]", "openRevisionSubmit");
        openRevisionOptions = createElementList("xpath=//div[contains(@class,'ant-select-item-option')]", "openRevisionOptions");
        exportProjectModalComponent = new ExportProjectModalComponent();
        // The select carries its own testid: antd no longer derives the input id from the form name, so the
        // field's id is autogenerated (_r_NN_) and the old merge_branches_form_targetBranch match is gone.
        mergeTargetBranchSelect = new WebElement(page, "[data-testid=merge-target-branch]", "mergeTargetBranchSelect");
        // The dropdown is an antd portal at body level and its options carry no per-branch testid,
        // so they are collected as a list and matched by text in selectMergeBranch.
        mergeBranchOptions = createElementList("xpath=//div[contains(@class,'ant-select-item-option')]//div[contains(@class,'ant-select-item-option-content')]", "mergeBranchOptions");
        copyProjectDialogComponent = new CopyProjectDialogComponent();
        configureCommitInfoComponent = createScopedComponent(ConfigureCommitInfoComponent.class, "xpath=//div[@role='dialog'][.//div[contains(@class,'ant-modal-title') and normalize-space()='Configure Git Commit Info']]", "configureCommitInfoComponent");
        configureCommitInfoShade = new WebElement(page, "xpath=//div[@role='dialog'][.//div[contains(@class,'ant-modal-title') and normalize-space()='Configure Git Commit Info']]", "configureCommitInfoShade");
        syncUpdatesDialogComponent = new SyncUpdatesDialogComponent();
        detailRoot = new WebElement(page, "[data-testid=project-detail]", "detailRoot");
    }

    public ProjectDetailPage openOverviewTab() {
        overviewTab.click();
        waitUntilSpinnerLoaded();
        return this;
    }

    /**
     * Opens the Files tab. Right after a project is created the detail screen finishes loading late and
     * resets to Overview, so the click is repeated until the tab really is open — the Add button exists
     * only there, which makes it a reliable marker.
     */
    public ProjectDetailPage openFilesTab() {
        detailRoot.waitForVisible(DEFAULT_TIMEOUT_MS);
        for (int attempt = 1; attempt <= TAB_SWITCH_ATTEMPTS; attempt++) {
            filesTab.click();
            waitUntilSpinnerLoaded();
            if (files.isOpen(DEFAULT_TIMEOUT_MS / 2)) {
                return this;
            }
        }
        files.waitForOpen(DEFAULT_TIMEOUT_MS);
        return this;
    }

    public ProjectDetailPage openHistoryTab() {
        historyTab.click();
        waitUntilSpinnerLoaded();
        return this;
    }

    // --- Branches tab (React project-detail; create/merge controls require the project to be OPEN) ---

    /**
     * Clicks an action in the project header (Open Revision / Close / Sync / Copy / Delete / Compare /
     * Export / Deploy). The header bar collapses trailing actions into an overflow menu as the window
     * narrows, so look there when the button is not on the bar.
     */
    public ProjectDetailPage clickHeaderAction(String actionLabel) {
        headerActions.clickAction(actionLabel);
        return this;
    }

    /**
     * Branches the project. Studio 6.4.0 removed the Branches tab and moved branching into the Copy
     * dialog, which opens in branch mode on a branching repository — so "create a branch" is a copy of the
     * project into a new branch, and it leaves the project on that branch.
     */
    public ProjectDetailPage createBranch(String branchName) {
        return createBranch(branchName, false);
    }

    public ProjectDetailPage createBranch(String branchName, boolean switchAfter) {
        String sourceBranch = getCurrentBranch();
        clickHeaderAction("Copy");
        copyProjectDialogComponent.waitForDialogToAppear().setBranchName(branchName);
        copyProjectDialogComponent.clickCopyButton();
        fillCommitInfoIfShown();
        waitUntilSpinnerLoaded();
        // Studio moves the project onto the branch it just created, so wait for that instead of forcing it.
        WaitUtil.waitForCondition(() -> branchName.equals(getCurrentBranch()), DEFAULT_TIMEOUT_MS, 500,
                "Waiting for the project to land on branch " + branchName);
        if (!switchAfter) {
            switchBranch(sourceBranch);
        }
        return this;
    }

    // Attempts to branch under a name the repository already holds; returns the dialog's error text.
    public String createBranchExpectingError(String branchName) {
        clickHeaderAction("Copy");
        copyProjectDialogComponent.waitForDialogToAppear().setBranchName(branchName);
        copyProjectDialogComponent.clickCopyButton(false);
        return String.join(" ", copyProjectDialogComponent.waitForErrors(DEFAULT_TIMEOUT_MS));
    }

    // Switches the project onto another branch via the branch switcher next to the branch label.
    public ProjectDetailPage switchBranch(String branchName) {
        openOverviewTab();
        overview.switchBranch(branchName);
        return this;
    }

    /**
     * Whether the repository holds this branch. The switcher offers every branch except the one the project
     * is already on, so the current branch is answered directly.
     */
    public boolean isBranchPresent(String branchName) {
        openOverviewTab();
        return overview.isBranchPresent(branchName);
    }

    /** Name of the branch the project sits on, without the Default tag the label adds to it. */
    public String getCurrentBranch() {
        openOverviewTab();
        return overview.getCurrentBranch();
    }

    // A first commit by a user raises the "Configure Git Commit Info" modal on top of the flow.
    private void fillCommitInfoIfShown() {
        if (configureCommitInfoShade.isVisible(HEADER_ACTION_PROBE_MS)) {
            configureCommitInfoComponent.fillCommitInfoWithRandomData();
        }
    }

    /**
     * Opens the merge dialog against another branch. 6.4.0 reaches it from the header's Sync action and asks
     * which branch to merge with, instead of the per-branch Merge action the removed Branches tab had.
     */
    public SyncUpdatesDialogComponent openMergeDialog(String targetBranch) {
        clickHeaderAction("Sync");
        mergeTargetBranchSelect.waitForVisible(DEFAULT_TIMEOUT_MS).click();
        selectMergeBranch(targetBranch);
        return syncUpdatesDialogComponent.waitForVisible();
    }

    /**
     * Picks a branch in the opened merge select. The options carry no per-branch testid, so they are matched
     * by their text — and the default branch reads as "masterDefault", the Default badge being part of the
     * option's text, so the branch name is matched as the start of the option rather than the whole of it.
     */
    private void selectMergeBranch(String targetBranch) {
        WaitUtil.waitForCondition(() -> !mergeBranchOptions.isEmpty(), DEFAULT_TIMEOUT_MS, 200,
                "Waiting for the merge branch options to appear");
        for (WebElement option : mergeBranchOptions) {
            String optionText = option.getText().trim();
            if (optionText.equals(targetBranch) || optionText.startsWith(targetBranch)) {
                option.click();
                return;
            }
        }
        throw new IllegalStateException("Branch '" + targetBranch + "' is not offered by the merge select");
    }

    // Reads the value assigned for a tag type from the Overview TAGS section (each tag renders as an
    // ant-tag "<type> → <value>"); returns the value span's text.
    public String getTagValueForType(String tagType) {
        openOverviewTab();
        return overview.getTagValueForType(tagType);
    }

    /**
     * The project's status. 6.4.0 restored the legacy wording — No Changes / In Editing / Viewing Revision
     * / Local / Closed / Deleted — and dropped the testid from the status pill, so it is read from the
     * Overview panel by its label.
     */
    public String getStatus() {
        return extractOverviewField("Status", "Repository");
    }

    // The Overview-right column concatenates its labelled fields into one text blob, in the order
    // Status / Repository / Path / Branch / Revision ID / Modified / Comment. Extracts one field's value.
    private String extractOverviewField(String label, String nextLabel) {
        openOverviewTab();
        return overview.extractField(label, nextLabel);
    }

    // Replaces the legacy Properties-tab getRevision() — the React Overview shows the FULL commit hash.
    /** Names of the modules the Overview tab lists for the project. */
    public List<String> getOverviewModuleNames() {
        openOverviewTab();
        return overview.getModuleNames();
    }

    /** Switches the Overview tab into edit mode and saves it without changing anything. */
    public ProjectDetailPage editOverviewAndSave() {
        openOverviewTab();
        overview.editAndSave();
        return this;
    }

    public String getOverviewRevision() {
        return extractOverviewField("Revision ID", "Modified");
    }

    // Replaces the legacy Properties-tab getModifiedBy()+getModifiedAt() — the Overview combines the author
    // and timestamp into a single "Modified" field (e.g. "German HarberJul 27, 2026 6:51 AM").
    public String getOverviewLastChange() {
        return extractOverviewField("Modified", "Comment");
    }

    /** Who last changed the project — the author part of the Overview "Modified" field. */
    public String getModifiedBy() {
        openOverviewTab();
        return overview.getModifiedBy();
    }

    /** When the project was last changed, as the Overview shows it (e.g. "Jul 27, 2026 10:26 AM"). */
    public String getModifiedAt() {
        openOverviewTab();
        return overview.getModifiedAt();
    }

    /**
     * The way a committed revision is named in the export window: "&lt;author&gt;: &lt;date&gt;". Lets a test
     * build the expected entry from the project's own Overview.
     */
    public String getLatestRevisionLabel() {
        return getModifiedBy() + ": " + getModifiedAt();
    }

    /**
     * Opens the project on an earlier revision, replacing the workspace copy — the "Open Revision" action.
     * The revision is named the way the revision lists name it: "&lt;author&gt;: &lt;date&gt;".
     */
    public ProjectDetailPage openRevision(String revisionLabel) {
        clickHeaderAction("Open Revision");
        openRevisionSelect.waitForVisible(DEFAULT_TIMEOUT_MS).click();
        openRevisionOption.format(revisionLabel).click();
        openRevisionSubmit.click();
        waitUntilSpinnerLoaded();
        return this;
    }

    /**
     * Opens the project on the revision at the given position in the list, newest first (1 = newest). Use
     * this rather than a label when the label comes from elsewhere: the editor's export window and this one
     * write the same commit's date differently.
     */
    public ProjectDetailPage openRevisionByPosition(int position) {
        clickHeaderAction("Open Revision");
        openRevisionSelect.waitForVisible(DEFAULT_TIMEOUT_MS).click();
        WaitUtil.waitForCondition(() -> openRevisionOptions.size() >= position, DEFAULT_TIMEOUT_MS, 250,
                "Waiting for the revision list to hold at least " + position + " entries");
        openRevisionOptions.get(position - 1).click();
        openRevisionSubmit.click();
        waitUntilSpinnerLoaded();
        return this;
    }

    /** Opens the Export window for this project (the action sits in the header, or in its Actions menu). */
    public ExportProjectModalComponent openExportDialog() {
        clickHeaderAction("Export");
        exportProjectModalComponent.waitForDialogToAppear();
        return exportProjectModalComponent;
    }

    // Replaces the legacy Properties-tab getPath() — the project's path-in-repository from the Overview.
    public String getOverviewPath() {
        return extractOverviewField("Path", "Branch");
    }

    // Replaces the legacy Properties-tab getRepository() — the design repository name from the Overview.
    public String getOverviewRepository() {
        return extractOverviewField("Repository", "Path");
    }

    // Revision comments on the History tab (each revision-comment-<hash>), newest first. Replaces the
    // legacy RepositoryContentRevisionsTabComponent.getRevisionDescription(i) loop.
    public List<String> getRevisionDescriptions() {
        openHistoryTab();
        return history.getRevisionDescriptions();
    }

    // Opens the repository revision comparison: selects the two newest revisions on the History tab, submits
    // the Compare dialog (which opens the diff in a NEW browser tab, the legacy showDiff.xhtml JSF page), and
    // returns a CompareGitRevisionsDialogComponent bound to that tab.
    /**
     * Opens the revision comparison. In 6.4.0 the Revisions tab no longer picks two revisions: the header's
     * Compare action opens the comparison screen in a separate window, where the revisions are chosen.
     */
    /**
     * Opens the comparison screen (a separate window) without choosing a revision — for checks that only
     * look at the screen itself, such as how the module dropdowns are ordered.
     */
    public CompareGitRevisionsDialogComponent openCompareWindow() {
        Page compareWindow = openCompareScreen();
        return new CompareGitRevisionsDialogComponent(compareWindow);
    }

    /** Clicks Compare and returns the window it opens (the screen is a popup, so wait for it as one). */
    private Page openCompareScreen() {
        Page compareWindow = page.waitForPopup(() -> clickHeaderAction("Compare"));
        settleCompareWindow(compareWindow);
        return compareWindow;
    }

    // The comparison screen is a JSF page that keeps loading after the window appears. It is opened with
    // window.open(width, height), which in a headless run can leave the popup sized so small that nothing
    // in it counts as visible — so give it a viewport of its own first.
    private void settleCompareWindow(Page compareWindow) {
        compareWindow.setViewportSize(COMPARE_WINDOW_WIDTH, COMPARE_WINDOW_HEIGHT);
        compareWindow.waitForLoadState();
        LOGGER.info("Compare window: url={}, title={}", compareWindow.url(), compareWindow.title());
        try {
            compareWindow.waitForLoadState(com.microsoft.playwright.options.LoadState.NETWORKIDLE,
                    new Page.WaitForLoadStateOptions().setTimeout(DEFAULT_TIMEOUT_MS));
        } catch (RuntimeException ignored) {
            // A busy page never reaches network-idle; the element waits below cover that.
        }
    }

    public CompareGitRevisionsDialogComponent openRevisionCompare() {
        Page compareWindow = openCompareScreen();
        CompareGitRevisionsDialogComponent compare = new CompareGitRevisionsDialogComponent(compareWindow);
        // The screen opens with nothing compared yet: pick the revision to compare against and run it.
        // (Its module dropdowns are RichFaces combos and stay hidden, so do not wait on them here.)
        // The left half is always the working copy, so index 0 (the newest revision) is what a project with
        // uncommitted edits must be compared against; comparing a committed project against its own HEAD
        // yields "File elements are identical" and no tree.
        compare.selectRevision(0);
        compare.clickCompareBtn();
        return compare;
    }

    // The newest revision's git hash, parsed from the first History entry's data-testid
    // ("revision-comment-<hash>"). Lets callers assert a new revision was committed (id changes).
    public String getLatestRevisionId() {
        openHistoryTab();
        return history.getLatestRevisionId();
    }

    public int getRevisionsCount() {
        openHistoryTab();
        return history.getRevisionsCount();
    }

    /**
     * Deletes a file: select it in the tree, then Delete from the preview pane's "More actions" menu and
     * confirm in the delete dialog. The tree node goes away asynchronously, so wait it out — otherwise a
     * following isFilePresent check races the removal and still sees the node.
     */
    public ProjectDetailPage deleteFile(String fileName) {
        openFilesTab();
        files.deleteFile(fileName);
        return this;
    }

    /**
     * Whether the project holds this file. Opens the Files tab itself: the detail screen can finish loading
     * late and drop back to Overview, which would leave the file tree out of the page.
     */
    public boolean isFilePresent(String fileName) {
        openFilesTab();
        return files.isNodePresent(fileName);
    }

    // Uploads a file into the project: Files tab -> Add -> Upload -> pick the file -> submit.
    public ProjectDetailPage uploadFile(String filePath) {
        return uploadFileAs(filePath, null);
    }

    /**
     * Uploads a file and stores it under a different name. A single-file upload exposes a Name field
     * (pre-filled from the picked file), which is how the legacy upload dialog's source→target rename maps
     * onto the React Files tab.
     */
    public ProjectDetailPage uploadFileAs(String filePath, String targetName) {
        return uploadFileAs(filePath, targetName, null);
    }

    /** Uploads into a folder of the project (e.g. "rules"); an empty folder means the project root. */
    public ProjectDetailPage uploadFileInto(String filePath, String targetFolder) {
        return uploadFileAs(filePath, null, targetFolder);
    }

    public ProjectDetailPage uploadFileAs(String filePath, String targetName, String targetFolder) {
        openFilesTab();
        files.uploadFileAs(filePath, targetName, targetFolder);
        return this;
    }

    /**
     * Whether the Files tab offers its Add menu (New folder / New text file / Upload). It is only rendered
     * for a user who may change the project's files, so this is how "can this user edit here?" is checked —
     * it replaces the old toolbar's Upload File / Add Folder buttons.
     */
    public boolean isAddFilesMenuAvailable() {
        openFilesTab();
        return files.isAddMenuAvailable();
    }

    /**
     * Replaces a file's content with another file: select it, Update from its actions menu, pick the new
     * file, confirm. Uploading a file with a different name is allowed but warned about.
     */
    public ProjectDetailPage updateFile(String fileName, String newFilePath) {
        pickUpdateFile(fileName, newFilePath);
        confirmUpdateFile();
        return this;
    }

    /** Opens the Update dialog for a file and picks the replacement, leaving the dialog open. */
    public ProjectDetailPage pickUpdateFile(String fileName, String newFilePath) {
        openFilesTab();
        files.pickUpdateFile(fileName, newFilePath);
        return this;
    }

    /** Confirms the Update dialog opened by {@link #pickUpdateFile}. */
    public ProjectDetailPage confirmUpdateFile() {
        files.confirmUpdateFile();
        return this;
    }

    /** Whether the update dialog warns that the chosen file has a different name. */
    public boolean isUpdateFileNameWarningShown() {
        return files.isUpdateFileNameWarningShown();
    }

    // Creates a folder (or path/to/folder) in the project via the Files tab.
    public ProjectDetailPage createFolder(String folderPath) {
        openFilesTab();
        files.createFolder(folderPath);
        return this;
    }

    // Folders and files are both tree nodes, so this also answers "is this folder present?".
    public boolean isFolderPresent(String folderName) {
        return files.isNodePresent(folderName);
    }

    public ProjectDetailPage reloadPage() {
        page.reload();
        waitUntilSpinnerLoaded();
        return this;
    }
}
